### ISSUE TITLE
Ask for help converting Clue Data

### ISSUE THREAD

**Issue by dktzde** [fabfabretti/clue.to.drip-menstruator.migrator#3]
Hello, I have finally received my data export from Clue. Unfortunately, the conversation with my data did not work, or the converted file could not be read by Drip. As the data is too private for me to post it here publicly, perhaps I can send you my data and you can take a closer look at it?

E-mail: sj92rwck@anonaddy.me

**Comment by fabfabretti** [comment]
Absolutely! I'm sending you an email immediately. Thank you for telling me about the bug, I should be able to investigate during the weekend :)

**Comment by dktzde** [comment]
It just works. Thank you so much!
