### ISSUE TITLE
What data is saved?

### ISSUE THREAD

**Issue by dktzde** [fabfabretti/clue.to.drip-menstruator.migrator#4]
Thank you for building this tool!

As this is quite sensitive data, I would be interested to know what is saved and whether the data conversation takes place on my PC or online.

**Comment by fabfabretti** [comment]
Hi! 🥰
Everything is done inside your browser, there is no server at all. I used Github's GitHub Pages feature to host the site, so it's all just a static page running a script that converts the file and lets you download it. :)

If you want to be really picky, GitHub Pages does store your IP address when visiting ([from docs](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#data-collection)):
> When a GitHub Pages site is visited, the visitor's IP address is logged and stored for security purposes, regardless of whether the visitor has signed into GitHub or not.

but the file conversion is completely local, so again the file is not uploaded anywhere 👌


If you would still prefer to run the whole project locally to avoid logging your IP, I suggest opening the project in VS Code and using the [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension to run the project in your browser!

(Also thank you for asking, I should probably add this to the readme 👀)
