### ISSUE TITLE
Error: "You need to upload a file first!"

### ISSUE THREAD

**Issue by CaptainMalu** [fabfabretti/clue.to.drip-menstruator.migrator#5]
I tried https://fabfabretti.github.io/clue-to-drip/
I cliecked the brows button, choosed the measurements.json file from clue and clicked on the download button.
I tested with chrome, firefox and vivaldi and all gave me a popup that I have to upload a file first. But there is no upload button.

![Screenshot from 2024-03-04 11-28-47](https://github.com/fabfabretti/clue-to-drip/assets/99020924/f88db187-f78b-4162-b32c-1134446a05c0)

**Comment by fabfabretti** [comment]
Hi! First of all, thank you for opening this issue. I'm a bit surprised, as the "browse..." button is the upload button and you seem to have uploaded the file correctly from your screenshot. Could you please take a screenshot of the console log (press f12 iirc and select "console") before and after uploading, to see if any error occurs there? For the sake of tackling one problem at a time, I'd ask you to use Firefox if possible. Thank you!


Edit: atm i don't remember if I left any debug print, as I haven't touched the code in a while. If so, please make sure to remove/hide any sensitive data!

**Comment by CaptainMalu** [comment]
there occurs an error in the moment of the upload.
![Screenshot from 2024-03-04 12-30-36](https://github.com/fabfabretti/clue-to-drip/assets/99020924/7e4813a3-18bf-4b57-8d01-b3c084704ecf)

Maybe that's the part in the measurment.json which leads to the error?
```
$ grep -nr measurements.json -ie pms -C5
4580-    {
4581:        "type": "pms",
4582-        "id": "uid",
4583-        "date": "2017-12-12",
4584-        "value": {
4585-            "option": "yes"
4586-        }
```

It has to be this entry.
Without it I get the download.
![Screenshot from 2024-03-04 12-55-00](https://github.com/fabfabretti/clue-to-drip/assets/99020924/e4caea52-5624-4f9f-a1a1-59c1a52d59e6)

**Comment by fabfabretti** [comment]
![immagine](https://github.com/fabfabretti/clue-to-drip/assets/59342704/49c35a7d-3a9f-4c8c-800e-c71246ea7b94)
Welp, it looks like the culprit was a missing dot! 😭 It should be fixed with the latest commit. Can you confirm?

**Comment by CaptainMalu** [comment]
yes, it's working fine now.
Thank you :heart_eyes_cat:
