### ISSUE TITLE
Unable to upload .json file

### ISSUE THREAD

**Issue by nstonall** [fabfabretti/clue.to.drip-menstruator.migrator#6]
Hi :)

When uploading the measurement.json file, I receive the following error message:

_You need to upload a file first!_

I've tried cloning the repo and doing it locally, but there is no response when uploading the file there.

All the best :)

**Comment by fabfabretti** [comment]
Hi! Thank you a lot for opening the issue. Could you please post a screenshot of the console log, to see if there is any hint there on what's going on? Thank you :)

**Comment by apaijmans** [comment]
Hi, same problem here, both in Firefox (with and without ad blockers) as well as with Edge. There also seems to be some sort of "convert/upload" button missing? At least, it only shows me the browse button and then underneath the download button. Havent tried to do it locally.

**Comment by fabfabretti** [comment]
Hi! Thank you for pitching in. As per previous message, I need a screenshot of the console log to see if there is any hint on what's going on - my current fear is that Clue changed their file structure, but I really need the console log screenshot to have an hint of what's going on.

About the browse button, once you browse and select the file the conversion happens automatically. Hence, all you need to do is click browse->select the file from the file picker->click download.

**Comment by apaijmans** [comment]
Here is a screenshot, unfortunatly I think it will be of very little help.

I was actually trying it with a very old Clue back up file from 2021... :-) So in that case I think a format change will probably not be the issue? I also tried to simply change the extension (.cluedata) to .json but that did not work either.

![screenshot](https://github.com/fabfabretti/clue-to-drip/assets/38758983/f14933c5-1c20-488f-941a-3363bbebf739)

**Comment by apaijmans** [comment]
Oh sorry, print screen from the console log... here you go

![screenshot](https://github.com/fabfabretti/clue-to-drip/assets/38758983/0ba2df66-7485-4005-9d93-aa891ab745b4)

**Comment by fabfabretti** [comment]
Hi again! Yes, I need a screenshot of the console log, not of the alert :') You should be able to access it by pressing F11 or F12 on the keyboard.

Well, if it's a very old backup file the issue could also be a change in format: this tool is developed for 2023 files, and if I recall correctly Clue has undergone a big change in backend and fronted structure recently. It's possible that the file structure has changed - even more so as I think Clue now gives you a .Json file, not a .cluedata. another way to check, if youre comfortable with it, would be to let me see (privately) the data science and see if it s correct.

**Comment by fabfabretti** [comment]
Just seen the screenshot. It looks quite unusual to me; could you confirm that this is the console that appears when pressing F11/f12 as a sidebar or as a bottom bar? Thanks!

**Comment by apaijmans** [comment]
Ah OK. The reason I tried the old file was because I did not use clue for years, and then tried to log in yesterday, only to find my history is gone.

This is what came up when pressing ctrl+shift+j. Never tried to pull up the console log so googled it... guess it was not the right console log, haha. I will add a screenshot from what I get when I hit F12...

**Comment by apaijmans** [comment]
![screenshot](https://github.com/fabfabretti/clue-to-drip/assets/38758983/ddfa7f3c-9a3e-4b4d-aecf-a0738279f73a)

**Comment by fabfabretti** [comment]
Yeah, I think this confirms that the data format is different than the one used for this project :c My advice would be to try to contact the Clue support email and ask them to convert the file to the newer version - in my experience, they are always very kind and might be able to help!

If their response is negative, feel free to write here again so we can have a look at the file and try to convert it :)
